version: '3'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_test
    ports:
      - "54322:5432"
    networks:
      - db_nw
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata: